language: node_js
node_js:
  - "node"
services:
  - mongodb
env:
  - MONGODB_URI=mongodb://localhost:27017/legal-aid-test
deploy:
  provider: heroku
  app:
    master: multnomah-legal-aid
    dev: multnomah-legal-aid-dev
    demo: multnomah-legal-aid-demo
  api_key:
    secure: K8EGHikdcuFvcdhKHnSqKbySse2caAk/FsPUitBjozPxXCa0oUc/vmrm6IXi27sV1oQcMHhDLaBuhmagD4qsP/BkOxtLMq99qJt5q/2+2wr3D/pLr6hCyJzIFleB6FIqug9Rq92EqixIriZJe/Xum1US+RxLdSKsaCj8ioUP6j5BnLkZ3VC5MVwDV/gmtXN/G/iHYbYt9wHVwPEmThEBmpQpae5Kjr84Sjsv55lkFToOqwI5GY42Y80RYhQIKNat5E8sx1RBQ2kztOv4/PT7MBhQd0yTAMtq65PwRVTuH8Xdt/QsI2IwiqekR+pc+V6K/iBJB6sumGI7A06RcX0YfRKPc64GGSRPp9vghdNq65KUrK+jnVPeyBLt/C9ekOtr7gG5zG0wwwK6H3C+NEdhl81yjzaRXkPdPRvNfj/f1uRbId5/vxR+1uSFPAKZlUZ0bySu9QeB92cFfS2kQRlKpDW+tyukLpIkIC4SBfwwCmWe+rtjEnD5VreWyqP8cvrjEPl5DwK2eWV/nlzOkGGh1B1RT+QAclLJRhTaz/RmwyFwfwDPeaK2d6G1JqpdViPaZYH9bynrEVeZG6ZWJmbfUJN/uxL2lC2r26MgvFMliK7cyFhtajPM8DOYRZcALBx43PYHNDjhhkVS8gbmNVtL39GGRd2XfgEKmpkgdvEwDvY=
