language: node_js
deploy:
  provider: heroku
  app: multnomah-legal-aid
  api_key:
    secure: f0szyF0RHimOwlAodXg3RPzNGjoejG8vdYDrNhFLffLZBegkqPxYKAQCJPKrziJDvq6IHICvmbKKxl21dclECju5h4NksfgnxmDJbqvpIB4C8Y1DYZh0DVnxJhsHi/VjGd+ST7+UMkPd1Q/PqXUw2Z7KISBzw//lZD2V23oqNC8BMYJ/cwUtwQXGTKiy4caNncXcAbLj0UZ4VNjtYLYrbJLuKEzh6LD9sroRSe223HY5kctTxdsxXiDkbuTeyOsAraeSVyYR0TJaAfhJd0AYH1yxpn+QqNc0UkqZTsZJukAGB1UT/jFXmE4URKtWV/+Cz2K5GDbO15qLOpRdg3JOPBGZ/NIUMy2LoQbZgKmEE7BVlRvWd4jynwsGU0WziOhayX5IlQVXsVLVA86WUlxCD93JFj4YnSAqX6TG3Vpwc+GJy9GJRb3QdPKDunjrzOGVRn9eLEeWT/OztMQv/xJVOl0p1Qg9avpIB7zeoYP3k2KZvv6TFlMBvRM/k7OqIlhZu95094sGLGI947i3SOJE2j2zOCU2C4p9jiCp76uIx9mtbDOqBdH2rhXYMvXC1gO9dRQ7x7z5Mr4dmk1x0aZzLQDRt+FUTzQFfbmaxjdlabqen33psp4kQTBK1+Ren2tGHpst9KofWXfd1KLFFpmDqXMdtClVjtyVSN3mw3pQGFM=
